# Generated by Django 6.0.1 on 2026-06-03 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
