# Generated by Django 6.0.1 on 2026-06-03 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
