# Generated by Django 6.0.1 on 2026-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_essay_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grade_level',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essay',
            name='paragraphs',
            field=models.IntegerField(default=3),
        ),
    ]
